README.md, lib/shell.js, lib/tasks.js
This fixes two issues:
1. when one of the pkgFiles doesn't exists, it created a new file with content of `undefined`
2. added config for distPkgFiles, because I don't want warning for files that are intended to be missing either from source repo, or dist repo. Also it caused an error with git add anyway if the file didn't exist. distPkgFiles default to distFiles if not defined to be backwards compatible.
=> Add distPkgFiles config

lib/config.js
According to lodash docs (https://lodash.com/docs/#defaultsDeep) defaults should go as a last argument to _.defaultsDeep() function.
=> Fix default options overriding

lib/tasks.js
The process of releasing with a distribution repository fails because tasks are passed as an array.
=> fix interactive dist release tasks

lib/tasks.js
The version of the dist repo is no longer in sync with the src repo's version.
=> make dist repo bump to the same version

.gitignore, README.md, lib/prompt.js, lib/tasks.js
Follow-up of #180 
The prompts should follow the options passed to the tasks runner.
@webpro Fell free to edit the README modifications, not sure how to best explain this.
=> Configurable prompts

CONTRIBUTING.md
I updated the docs to work in a "copy paste" manner, the ssh one required a key, while the https one does not.
=> changed from ssh to https

lib/tasks.js
Fixed dist.tag not working when src.tag is disabled.
See issue #333
=> Fixed dist.tag not working properly

.travis.yml
We should also test the current stable Node.js version which is currently 11.
=> ci: test Node.js 11

lib/github.js
The latest version tries to reference empty `this` in github.js.
=> fix(github): prevent error referencing this from arrow function

lib/config.js, lib/npm.js, package.json, test/config.js, test/npm.js, test/tasks.js
This PR adds support for npm's `publishConfig.registry` option.
Related docs:
- https://docs.npmjs.com/files/package.json#publishconfig
- https://docs.npmjs.com/misc/config#registry
Currently `release-it` fails when publishing to a registry other than the default because [this sanity check](https://github.com/webpro/release-it/blob/10.1.0/lib/npm.js#L58) does not take take into account `publishConfig.registry`.
Additionally, the [output after a successful publish](https://github.com/webpro/release-it/blob/master/lib/tasks.js#L164) makes [strong assumptions on the default registry](https://github.com/webpro/release-it/blob/10.1.0/lib/npm.js#L67).
=> Support publishConfig.registry

lib/changelog.js, lib/shell.js
Hi @webpro , this PR about #472 📝 
Contents of tweak: The caller side can specify `{ isWrite: false }` as option in `shell.runTemplateCommand`.
When using "Conventional-Changelog" for the `scripts.changelog`, the content of this PR(#460) is actually necessary. This is probably because the "release-it" does not actually execute the git operation in dry-run mode, so the "Conventional-Changelog" side can't detect the changes. 💭 
About `-u` flag is [here](https://github.com/conventional-changelog/conventional-changelog/blob/97ad96fe893bd5b40ec52e24fe46f4f9cd357a1a/packages/conventional-changelog-cli/cli.js#L40)
=> change to execute scripts.changelog even in dry-run mode

README.md
Otherwise the changelog would be empty
=> Add the `-u` flag to the `conventional-changelog` example

lib/npm.js, test/npm.js, test/tasks.js
Firstly thanks for adding support for `publishConfig.registry`.
This PR adds a fix for [#471](https://github.com/release-it/release-it/pull/471).
We have a custom NPM service powered by [verdaccio](https://verdaccio.org/), and the registry is like http://192.168.0.1:1234. 
Currently the validation of `this.shell.run('npm ping')` can not get passed.
Thanks.
=> Add custom registry for `npm ping`

README.md
Using `.release-it.js` instead of `.release-it.json` was something that helped me immensely, I think this possibility deserves to be documented directly.
=> Add note in readme about JS config files

README.md, docs/recipes/auto-changelog.md
Fixes #480.
The main source of confusion was the fact that the `-p` option was missing in the auto-changelog usage suggestion.
I also added some explanations to the script hooks which would have helped me, so probably will help others.
By the way, what is the difference between the `afterBump` and `beforeStage` hooks? That is still not so clear to me. Thanks.
=> Improve docs on auto-changelog usage

lib/github.js, lib/tasks.js, test/github.js, test/stub/github.request.js, test/tasks.js
This PR moves the actual publishing of the GitHub release to after the release assets have been uploaded.
This is important because Github Action triggers a release on publish, so it is possible that release assets might not be visible to the action, as they are yet to be uploaded.
see #https://github.com/release-it/release-it/issues/495
=> Add initial draft step to GitHub release

lib/plugin/npm/npm.js
I ran into a Timeout issue when using a 3rd Party NPM registries (JFROG Artifactory).
I noticed that the additional argument `--registry` is missing for this check function, so added it in the same fashion as it was made for e.g.`isAuthenticated()`
=> Fix timeout issue with 3rd party npm registries.

lib/plugin/git/Git.js
Just count commits from the first one to HEAD.
May require additional unit tests
=> Fix #557 use just HEAD for counting if no tag yet

docs/recipes/auto-changelog.md, docs/recipes/changelog-compact-template.hbs
Storing the auto-changelog template as a separate file may help other to use it easily form this repository:
```
auto-changelog --stdout --commit-limit false --unreleased --template https://raw.githubusercontent.com/release-it/release-it/master/docs/recipes/changelog-compact-template.hbs
```
This is handy because some people do not want to maintain it's own auto-changelog template and are happy with the default one.
=> Add auto-changelog template file to be used directly from the repository

docs/gitlab-releases.md
Also fixed typo of GitHub when documentation is about GitLab.
=> Fix links to documentation

CHANGELOG.md, config/release-it.json, docs/git.md, docs/prerequisites.md, lib/plugin/git/Git.js, test/git.js, test/shell.js
When the branch is tracking upstream branch and `git.pushRepo` was
not customized, there should push directly to upstream branch instead
of pushing to `origin` which might not be the one that matches tracking
information or even exist.
Resolves #608
=> Don't include repo on push if branch has upstream (for v13)

docs/npm.md, lib/plugin/npm/npm.js, test/npm.js, test/tasks.js
Had three issues here:
* The docs suggested scoped packages would be published as private,
however this behavior was changed in c3976bf
* The docs show config to be added to the package.json, which can be
easily misunderstood as what needs to be added to the .release-it.json
file (all the other examples reference the release-it config)
* The links in the docs were dead
This commit reverts the behavior introduced by c3976bf because the
behavior is surprising and dangerous.
It also updates the documentation to fix the links and show how to
configure release-it first (before the note about a package.json file).
=> Fix scoped packages publish behavior

lib/plugin/GitBase.js, test/github.js
Hello everyone,
I propose a small improvement for your great tool 😊 
In my git config, I implemented some git url aliases including the following one:
```txt
[url "git@github.com:"]
insteadOf = "gh:"
```
Which allows me to clone like this: `git clone gh:SuperITMan/stark.git`.
If I want to get the url of my remote with `git remote -v`, I obtain: 
```bash
origin  git@github.com:SuperITMan/stark.git (fetch)
origin  git@github.com:SuperITMan/stark.git (push)
```
But in release-it, currently, when the tool tries to get the remote url, it uses the command `git config --get remote.origin.url` which gives `gh:SuperITMan/stark.git` instead of `git@github.com:SuperITman/stark.git`.
See the error I get when I try to do a release (the url is wrong and GITHUB_TOKEN variable is useless):
```bash
npm …
```
=> feat(git): add support for git url aliases

lib/plugin/GitBase.js, test/git.init.js
Hi folks, here's a bug fix for `tagName` config which is being ignored in `v13.5.0` :)
=> [bug fix] tagName being ignored

test/util/index.js
Prior to this change the implementation in `lib/tasks.js` passes the latest version in to the `Plugin.prototype.getChangelog` method:
https://github.com/release-it/release-it/blob/81136a214eeb744dd6d6d48626f8a4786a55b39c/lib/tasks.js#L70-L71
However the test runner in `test/util/index.js` did not:
https://github.com/release-it/release-it/blob/81136a214eeb744dd6d6d48626f8a4786a55b39c/test/util/index.js#L38-L39
=> Ensure test runner passes latest version to `getChangelog`

.github/workflows/test.yml
This effectively removes the (IMHO needless) `-latest` suffix in the names of each of the Cross OS tests. The node versions were cutting off when I was viewing the CI status on prior pull requests.
Before:
After:
=> Simplify GitHub Actions CI Job Names

.github/workflows/test.yml
Based on the prior setup it seemed like we only wanted to test LTS versions of Node. Since 14 just came out and _will eventually_ be an LTS, I figured we could add it to the CI setup...
=> Add Node 14 to GitHub Actions CI.

test/util/index.js
As of release-it@13.5.3 `latestTag` and `tagName` are available on the global configuration object (aka `this.config` within a plugin instance). These new global config context values make authoring plugins that care about these values (but don't "control" them) much easier.
Unfortunately, prior to these changes they were not setup and available from within the test harness. Since these values are always present when used outside of the test harness having them missing while testing means that plugins are forced to handle fallback scenarios for when they are not set (which is extremely unlikely to happen in reality).
This commit sets `latestTag` and `tagName` in the test harness. It currently uses the values for `latestVersion` and `version` for that (because the test harness does not …
=> Set `latestTag` and `tagName` on global config in test harness.

lib/plugin/git/Git.js
Fix for #687
I tried to add some additional test coverage, but for some reason the behavior which I can reliably reproduce in a node terminal (see notes in #687) was only inconsistently reproducible in the tests I tried. I'm not yet clear what it is about the testing environment that causes this, but the existing tests show that the change still works for existing cases, so perhaps that's good enough?
=> Improve isWorkingDirClean() check for projects with generated code

lib/plugin/version/Version.js, test/plugins.js, test/version.js
@webpro This PR tries to solve #714 - which I've introduced via #707 
Problem was that the 'patch' default in the CI mode previously did not had an effect in a prerelease continuation scenario. With #707 the default patch increment is applied.
To solve this the prelease shortcut has to be detected first. Only if it's not the prerelease shortcut the increment can be set to 'patch' in CI mode. To be able to implement this evaluation order I added a optional isCI flag to the incrementVersion method.
I also added some additional tests to verify the fix.
=> Fix prerelease continuation increased patch version in CI mode

README.md, lib/config.js
Hi there. This is a super-simple pull request that adds to the config.js library file to look for `release-it.cjs` in addition to `release-it.js` as a possible configuration file.
In our company we use `release-it` to help automate versioning and packaging a bunch of different repositories. Most of the repos use the same release configuration, and as part of a general consolidation effort we'd like to look at a single configuration with the ability to override it if necessary.
We trying out a new mechanism where we are storing the `release-it` configuration in a `.js` file and putting in a little bit of logic to make overrides dead simple. 
A typical configuration file in one of the repos might look something like this:
```js
const releaseItConfig = …
```
=> Update the config.js library file to look for release-it.cjs

docs/ci.md
This PR will, once merged, add a few extra lines of documentation. First, suggesting a new command to edit the .npmrc file for auth purposes using NPM's own config set instead of manually editing the file, and the second is a bit of clarification for Circle CI users that might find problems in the git steps of the release process.
=> docs(ci): add alternative .npmrc command and circle ci details

docs/recipes/auto-changelog.md
Otherwise the hook fails to update the changelog
=> docs: add missing template flag to auto-changelog

docs/plugins.md
Before it was getting a buffer, but it was meant to get a string, so an encoding needs to be specified.
=> Fix: example plugin reads file as string

.eslintrc.json, config/release-it.json, docs/gitlab-releases.md, lib/plugin/gitlab/GitLab.js
When running a private GitLab instance protected with a certificate issued by a private certificate authority, you can now specify a root CA certificate file with `gitlab.certificateAuthorityFile` option.
=> feat: Adding certificateAuthorityFile option for GitLab releases

docs/git.md
In previous version hooks won't fire with `push:false` option.
```Note that hooks like after:git:release will not run when either the git push failed, or when it is configured not to be executed (e.g. git.push: false). See execution order for more details on execution order of plugin lifecycle methods.```
=> Changed git docs with correct hook

lib/plugin/github/GitHub.js
Hi, there 👋
I'm using this package in a Github enterprise.
When I use [github release](https://github.com/release-it/release-it/blob/master/docs/github-releases.md) automatically, It's working well.
But if it's manual, The generated url is always github link. (not enterprise link)
So I added host information to `generateWebUrl` function.
For a similar code convention, I referred to the following.
https://github.com/release-it/release-it/blob/7286e6ec39a00c4e88a586cb0dd420218f690c4e/lib/plugin/github/GitHub.js#L152-L153
Thank you for your hard work.
=> feat : add a host info when generating web url

docs/npm.md, lib/plugin/npm/npm.js
=> Allow running npm version with arg --allow-same-version

package.json
=> fix: downgrade `inquirer` from 8.2.2 to 8.2.0 to avoid dropping Node 10 support

.github/workflows/test.yml
I believe CI was failing to test the different Node versions that should be supported because of this missing step.
https://github.com/actions/setup-node#usage
Related to: #886
The Node 10 test should fail for this PR until #887 is merged.
=> test: fix CI test for different Node versions

lib/plugin/github/GitHub.js, package.json, test/github.js
Based on a recent change in Octokits docs[1], in order for it to use a
configured proxy you must pass another request.agent into the Octokit
constructor. This change adds the `proxy-agent` lib as suggested by
Octokits docs.
Note that with this implmentation, the `http_proxy` or `https_proxy`
environment variables alone will NOT work. Instead one must explicitly
set the value in the `github.proxy` option passed to release-it. This is
to stay inline with current behavior[2].
[1] https://github.com/octokit/octokit.js/commit/2090c85b5addf33b93dac74930312593622c08b8
[2] https://github.com/release-it/release-it/blob/14.14.2/docs/github-releases.md#proxy
=> Fixes github.proxy not working (#863)

lib/plugin/git/Git.js, test/git.js
Due to git.commitMessage being optional t is now possible to amend previous commit instead of
creating a new one.
Example usage:
release-it minor --git.commitArgs='--amend --no-edit' --git.commitMessage=''
fix #907
=> feat(git): make commitMessage optional parameter in git commit

package.json
This change slightly adjusts the exports in this repo's package.json in order to expose the required test utilities to consumers.
While the alias provided in https://github.com/release-it/release-it/commit/529bc1fde988515079efdb0a8bd2e0fc7360c17e technically works for ESM consumers, it won't work for CJS consumers as that path isn't a real path on disc.
Relates to #920 and tweaks https://github.com/release-it/release-it/commit/529bc1fde988515079efdb0a8bd2e0fc7360c17e to use correct path.
=> fix: Fixes exports to correctly export test utils

README.md
We've moved two plugin packages under a new org, `@release-it-plugins`, and renamed them. This PR updates the README to reflect those renames.
=> Updates README with new plugin package names

lib/plugin/factory.js, test/plugin-name.js, test/plugins.js, test/tasks.interactive.js
=> Fixes loading scoped plugins to ensure name is preserved

lib/cli.js, lib/config.js, lib/index.js
Add --changelog option to cli to be able to only get the change log similar to what --release-version do but for change log
=> feat(cli): add new --changelog option

lib/plugin/GitBase.js, lib/plugin/git/Git.js
for this issue https://github.com/release-it/release-it/issues/820
=> add branchName for template

config/release-it.json, docs/git.md, docs/pre-releases.md, lib/plugin/GitBase.js, lib/plugin/GitRelease.js, test/git.init.js
Hello,
There is a small problem in which it isn't possible to exclude certain tags when generating new releases.
For example this image:
Latest commit has tag `15.5.2-rc.0`, previous one has tag `15.5.1`. I ran the `git describe --tags --abbrev=0` as is used in [GitBase](https://github.com/release-it/release-it/compare/master...drmartini7:release-it:master?expand=1#diff-3a1c94688e9b16bb758da2b80710601a1966f46fd660ce47c8512a69e66d8715R97), only changing the match argument:
- No match, obviously just returns latest tag;
- `--match='[!-]*'`, as suggested [here](https://github.com/release-it/release-it/compare/master...drmartini7:release-it:master?expand=1#diff-1397ee01a8fd0f298ff6bb0e96747733fde00ced7fd635441e5b562228c62ff1L58), it just returns the latest tag. Why it doesn't work eludes me, …
=> feat(git): added option to use --exclude option on git describe

lib/plugin/npm/npm.js
With v9.0.0 release [npm][] has changed the CLI commands for package access. While previously it was `npm access ls-collaborators` and the output was a JSON object, now it is `npm access list collaborators` and the output is plain text unless `--json` flag is provided.
This commit adds support for npm v9.0.0 while keeping support for older npm versions.
[npm]: https://github.com/npm/cli/commit/9c32c6c8d6fc5bdfd6af685731fe26920d7e5446
=> Fix `npm.isCollaborator()` on npm v9

lib/plugin/gitlab/GitLab.js, package.json
This PR remove the dependency of form-data package
`FormData` exists built in to NodeJS now in v18+ now.
Both `got` and `node-fetch` support encoding a spec'ed `FormData` themself now, and the `form-data` package is now considered as legacy by `node-fetch` and `got`s standards. `form-data` haven't been updated for a long while and it lacks many methods and don't really follow the specification.
`node-fetch` ships with a polyfilled FormData and ways to get Blob/File like objects backed up by the filesystem that is read lazily when needed (thanks to the `fetch-blob` package). The native FormData provided by NodeJS themself do also support Blob / File like objects and dosen't need to be strictly the same instances of `globalThis.Blob` so `node-fetch` can now also export the native `FormData` …
=> fix: use spec'ed formdata

docs/plugins.md
Fixed name of property `peerDependencies` on plugins README.
=> Fixed plugins README on `peerDependencies` property

.gitignore, config/release-it.json, lib/plugin/git/Git.js, test/git.init.js, test/util/helpers.js
Allows providing commits path when `requreCommits: true`.
Makes release-it configuration aligned with `@release-it/conventional-changelog` plugin:
```javascript
const releaseItConfig = {
plugins: {
'@release-it/conventional-changelog': {
preset: 'conventionalcommits',
path: '.',
gitRawCommitsOpts: {
path: '.',
},
},
},
git: {
requireCommits: true,
commitsPath: '.',
[...]
},
[...]
};
```
This configuration is handy when release-it is executed in npm workspace where only related commits should be taken into account.
=> feat: configurable path in git rev-list

bin/release-it.js, config/release-it.json, lib/plugin/git/Git.js, lib/util.js, test/git.init.js
This PR introduces a possibility to exit with 0 code (success) when `requireCommits: true` and no commits available.
Why this is handy:
Alongside with this PR https://github.com/release-it/release-it/pull/982 it will make release-it a monorepo best friend.
Some times it is OK not to have commits related to a certain workspace. Exit with error may stop the pipeline execution, depending on CI configuration.
This particular feature is inspired by monorepo managed by turborepo where every workspace has a `"release": "release-it"` npm script in `package.json`.
When turbo release pipeline is executed failing releases are:
- terminating pipeline execution
- preventing execution results to be cached
I my case, right now, a custom script, which checks if there commits that touch a specific …
=> feat: make exit 0 possible when commits required but missing

docs/github-releases.md, docs/gitlab-releases.md, lib/plugin/GitRelease.js, test/github.js
Let me know if I've missed something or if you want to expand this to other places.
Fixes #870
=> Support function for configuring github/gitlab releaseNotes

docs/npm.md
[release-it-yarn-workspaces](https://www.npmjs.com/package/release-it-yarn-workspaces) is now deprecated and moved under `@release-it-plugins`.
This PR updates the `npm.md` docs with the change.
Let me know if anything should be changed.
=> Update docs with the new workspaces plugin name

lib/index.js
Hi! 
Love this package, using it in our CI infrastructure!
Added a small change to support case when plugin returns null in `getIncrementedVersion` (this is possible, [example one](https://github.com/release-it/conventional-changelog/blob/master/index.js#L58), [example two](https://github.com/release-it/conventional-changelog/blob/master/index.js#LL139C48-L139C69))
=> Skip version release if plugin `getIncrementedVersion` return null

docs/ci.md
- CI_BUILD_REF_NAME has been depreciated use CI_COMMIT_REF_NAME
=> Update gitlab CI documentation (closes #1006)

lib/plugin/Plugin.js, lib/util.js, test/utils.js
Initially, I attempted to modify the "source" order in `Object.assign`, but upon further consideration, I realized that utilizing a deep merge strategy would be a safer approach.
=> fix: use deep merge strategy for context and options in Plugin

lib/plugin/github/GitHub.js
Using `await open(url, { wait: true })` can solve the issue of the browser not automatically opening on Windows devices. Additionally, a prompt has been added to the terminal to display the GitHub Release web interface URL, allowing users to manually copy and paste it into the browser for further operation if the browser does not open automatically.
=> fix: unable to open the browser automatically on Windows system

docs/github-releases.md
Given this code:
https://github.com/release-it/release-it/blob/38193c37f6e570907eb8c7df02a9a41714eba509/lib/plugin/github/GitHub.js#L375C1-L379C51
I think that the parameter to set has to be `github.comments.submit` instead of `github.comments`
=> fix: name of param to enable comment functionality

README.md
Close #1053
Add release-it-changelogen and release-it-dotnet
=> chore: add plugins to readme

lib/plugin/github/GitHub.js
fix: #1070
```bash
northword@Yoga-Northword MINGW64 /d/Code/Zotero/zotero-format-metadata (main)
$ pnpm release --github.release --dry-run --VV --no-git.requireCleanWorkingDir
> zotero-format-metadata@1.6.17 release D:\Code\Zotero\zotero-format-metadata
> release-it "--github.release" "--dry-run" "--VV" "--no-git.requireCleanWorkingDir"
$ git rev-parse --abbrev-ref HEAD
$ git config --get branch.main.remote
$ git remote get-url origin
! git fetch
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git describe --tags --match=v* --abbrev=0
$ git symbolic-ref HEAD
$ git for-each-ref --format="%(upstream:short)" refs/heads/main
$ git rev-parse --abbrev-ref HEAD  [cached]
$ git config --get branch.main.remote  [cached]
$ git remote get-url origin  [cached]
! git fetch
$ git rev-parse --abbrev-ref …
```
=> Parse issues from commit log instead of changelog

lib/plugin/github/GitHub.js
closes #1057 
As described in the issue #1057 the comments aren't added in CI environment.
Here is a simple fix for it.
I was trying to understand why they weren't enabled but actually I do not see any reason.
=> Add comment on PRs in CI environments

lib/plugin/git/Git.js
=> Catch and log errors thrown in `rollbackTagPush()` in Git plugin

lib/index.js, lib/util.js, test/git.init.js
Updating the flow to when requireCommits is true but requireCommitsFail is set as false and no commits are available, instead of returning ERROR There are no commits since the latest tag. just returns There are no commits since the latest tag. and remove the ERROR string as that is misleading.
Fixes https://github.com/release-it/release-it/issues/1095
=> Exit without error message when requireCommits is true but requireCommitsFail is false and no commits are available 

package.json, schema/git.json, schema/github.json, schema/gitlab.json, schema/npm.json, schema/release.json, schema/test.json
#1076 
Add json schema for configure release-it.json
=> feat: Add json schema

package.json
- Add `types` folder to `files` in `package.json`, so they are effectively shipped in npm package
- Correctly export them through `exports` in `package.json`
=> fix: ship & export types

lib/plugin/gitlab/GitLab.js, package-lock.json, package.json
Promise.allSettled has been supported since node v12 (https://node.green/#ES2020-features--Promise-allSettled) and release-it only supports `"node": "^18.18.0 || ^20.9.0 || ^22.0.0"`. We can safely drop the dependency on `promise.allsettled` ponyfill. Moreover, the `promise.allsettled` dep is pulling 4MB of unnecessary code.
Also bumps inquirer which recently dropped unnecessary dependencies. This will reduce release-it's install size by over 13%.
PS: Using both `node-fetch` and `got` seems wrong - just one will be sufficient. Moreover, they can probably be replaced by node's built-in fetch which was unflagged in node v18.0.
=> chore: drop dependency on promise.allsettled

types/config.d.ts
Hit a type error when using `requireBranch`. The correct type seems to be a `string`, `undefined`, or `false`, which is apparently the default.
=> fix(types): requireBranch is either a string, false, or undefined

package-lock.json, package.json
`release-it` has transitive dependency on `ip` package (https://github.com/indutny/node-ip) which was recently reported as vulnerable. 
Here is the description of the **dependabot** alert raised by GitHub on one of our private repos which uses `release-it` 
> The ip package through 2.0.1 for Node.js might allow SSRF because some IP addresses (such as 127.1, 01200034567, 012.1.2.3, 000:0:0000::01, and ::fFFf:127.0.0.1) are improperly categorized as globally routable via isPublic. NOTE: this issue exists because of an incomplete fix for https://github.com/advisories/GHSA-78xj-cgh5-2h22.
`pac-resolver` and `socks` packages were upgraded to get rid of ip package
https://github.com/TooTallNate/proxy-agents/pull/281
https://github.com/JoshGlazebrook/socks/pull/94
Alongside also upgraded …
=> fix: vulnerable packages

config/release-it.json, docs/gitlab-releases.md, lib/plugin/gitlab/GitLab.js, schema/gitlab.json, test/gitlab.js, types/config.d.ts
This PR adds a new flag to the gitlab config options: `secure`.
If the value of this flag is **not** `undefined`, it will be forward to https request library (`got`), which in turn also forwards it to node's `https.request` method as the `rejectUnauthorized` flag.
The `rejectUnauthorized` flag is `true` by default. When its value is `false`, it allows node to make https requests to servers without verifying the server certificate against the list of trusted CA's.
The goal of this PR is to reduce the effort to create gitlab releases for teams working with self-hosted private gitlab instances, skipping the need of having to pass CA certificates around.
Fix: #1125
=> feat: add secure flag to gitlab config

.release-it.json, docs/github-releases.md, lib/plugin/github/GitHub.js, schema/github.json, test/stub/github.js, types/config.d.ts
In a project we create non-latest support release regularly. It is annoying to reset the latest release everytime.
Unfortunately release-it does not expose the make_latest flag from  the [GitHub API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release).
This PR exposes this option.
Something to think about: Should the `make_latest: "legacy"` option even be exposed or should it be renamed?
I tested this here: https://github.com/sirchnik/test-npm
=> feat(github): expose github make_latest flag

config/release-it.json, docs/gitlab-releases.md, lib/plugin/gitlab/GitLab.js, schema/gitlab.json, test/gitlab.js, test/stub/gitlab.js, types/config.d.ts
Gitlab started to use a [new URL format](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/150939) for uploaded assets in version 17.1 and since version 17.2 all new uploaded assets are [no longer accessible via the old URL format](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/156939), which means that uploaded assets are no longer accessible from the links in the release.
This PR introduces a new flag for Gitlab which allows the user to choose which URL format release-it should use when publishing the uploaded assets in a new release.
=> Fix uploaded assets URL for Gitlab version >= 17.2

docs/github-releases.md, lib/plugin/GitRelease.js, lib/plugin/github/GitHub.js, package-lock.json, package.json, schema/github.json, test/github.js, test/stub/github.js, types/config.d.ts
In my open source projects, I am extensively using release-it. Before that I used to use GitHub Action to make the release on GitHub which also created GitHub discussion for me.
But when I started using release-it, I did not found any option to auto create GitHub discussion on GitHub release.
With this PR, `discussion_category_name` has been exposed to the [GitHub API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release).
Hopefully this feature would be helpful to others.
=> feat(github): added support to create github discussion on release creation

lib/plugin/gitlab/GitLab.js, package-lock.json, test/gitlab.js, test/tasks.interactive.js, test/tasks.js
Replacement for release-it#1116  as per https://github.com/release-it/release-it/pull/1116#issuecomment-2405765425 with:
- Functional unit tests. 🤞 
- Support for `tag_message` to [GitLab API](https://docs.gitlab.com/ee/api/releases/#create-a-release) via `git.tagAnnotation`.
=> feat: create tag via Gitlab release (#1115)

lib/plugin/gitlab/GitLab.js
The `got` npm package [sets the proper](https://github.com/sindresorhus/got/blob/main/documentation/quick-start.md?plain=1#L60) `Content-Type` header when the body of a request is set to `json`. This behavior [was not ported](https://github.com/release-it/release-it/commit/696f0821fa871a794dba9eabdcc960554f073eab#diff-44f297bf9ddf782cf7057c9b2755dedcb77fd7e168cbd354690eb933a9b5022bR166-R169) when `got` and `node-fetch` were removed in favor of NodeJS' native `fetch` API.
This PR fixes this.
=> Add proper Content-Type header to fetch requests

docs/git.md
Make it even more clear that Tag Match does not accept regexes but globs by removing the unnecessary escapes
=> Improve docs on Tag Match

README.md, docs/changelog.md, docs/recipes/git-cliff.md
It appears `auto-changelog` has gone a bit stale (e.g. https://github.com/cookpete/auto-changelog/issues/293 and https://github.com/cookpete/auto-changelog/issues/291). After struggling with getting auto-changelog to properly sync up the current version in `CHANGELOG.md` and the release on GH within a monorepo, I ended up switching to [git-cliff](https://git-cliff.org), which appears to be a more active project. This PR adds some example config for using git-cliff with release-it.
=> Add git-cliff example

lib/plugin/gitlab/GitLab.js
As noted in [a comment on #1172][1], switching to the use of the native fetch API broke uploading release assets to GitLab by hard-coding the Content-Type header to "text/plain". The [recommended approach][2] is to avoid setting the Content-Type header at all and let the fetch API implementation set it so as to ensure that the correct boundary expression is included.
~~Add a flag to the `request` function to allow explicitly disabling setting the Content-Type header.~~ Update the `request` function to avoid setting the Content-Type header if the body is an instance of `FormData`. The default behaviour is to set the header as before but we disable setting the header only in the `uploadAsset` function.
The bug is blocking a [feature in our …
=> fix(gitlab): don't set Content-Type header when uploading release assets

config/release-it.json, docs/gitlab-releases.md, lib/plugin/gitlab/GitLab.js, schema/gitlab.json, test/gitlab.js, test/stub/gitlab.js, types/config.d.ts
This PR is for adding the ability to use GitLab's Generic Package Repository for uploading assets to the repo for use in the release. The current implementation uses the Markdown Uploads API which isnt ideal. That implementation is for use in wikis, readmes, etc. Using the Generic Package Repository is more inline with releases and allows more versioning control in the UI. 
By default, this feature will not change the default behavior so current implementations will not be broken. To use the new feature you set the option  `useGenericPackageRepositoryForAssets` to `true` (defaults to `false`) and you can define the package name by setting `genericPackageRepositoryName` (defaults to `release-it`). 
Fixes #1154
=> GitLab Generic Package Repository for assets

docs/configuration.md, lib/config.js, lib/index.js, schema/release-it.json, test/config.js, test/tasks.interactive.js
This pull request introduces the ability to extend configuration from a remote source, specifically GitHub repositories, and includes several related changes to the codebase, documentation, and tests.
* [`docs/configuration.md`](diffhunk://#diff-17ed18489a956f326ec0fe4040850c5bc9261d4631fb42da4c52891d74a59180R90-R108): Added documentation for the new `extends` option that allows extending configurations from remote GitHub repositories.
* [`schema/release-it.json`](diffhunk://#diff-351d879d6af18de4b75acfc02e1d443c8ffb3438f9d1176537f8eafeb7e46f4dR12-R15): Added the `extends` property to the JSON schema to specify a configuration to extend.
* [`lib/config.js`](diffhunk://#diff-d5109920b34c2b2e141bd41232d8876432a17479c388e142d8a036bb7b36ea62L6-R6): Introduced `fetchConfigurationFromGitHub` …
=> feat: add capability to add extends configuration to release-it

schema/git.json
The JSON Schema for the `git` plugin had `addUntrackedFiles` set as a string type when it should be a boolean. This leads to a warning when setting this option in `.release-it.json`. This only applies when a JSON file is used for configuration.
=> fix(json-schema): change `addUntrackedFiles` to boolean

bin/release-it.js, lib/args.js, schema/git.json, test/args.js
Don't use "false" string as true value.
For example `release-it --git.commit=false` was parsed as `true`, because string `"false"` is non-empty.
=> fix: parse boolean values from command line

lib/plugin/github/GitHub.js
probably fixes:
* https://github.com/release-it/release-it/issues/1191
* https://github.com/release-it/release-it/issues/1238
side note: 
For some reason the octokit logger will not ~initialize~ default to `{}` when it's null
this is from `node_modules/@octokit/core/dist-src/index.js` 🤷 
```js
function createLogger(logger = {}) {
if (typeof logger.debug !== "function") {
logger.debug = noop;
}
if (typeof logger.info !== "function") {
logger.info = noop;
}
if (typeof logger.warn !== "function") {
logger.warn = consoleWarn;
}
if (typeof logger.error !== "function") {
logger.error = consoleError;
}
return logger;
}
```
=> fix: set octokit log option to {} instead of null

README.md, docs/npm.md
Added new section to the npm docs describing how to get OIDC to work. Validated with https://github.com/photostructure/batch-cluster.js/actions/runs/17221702675/job/48859283308 (woot!)
=> Add OIDC publishing docs
